// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.asrouter.providers.snippets", "{\"id\":\"snippets\",\"enabled\":true,\"type\":\"remote\",\"url\":\"https://snippets.cdn.mozilla.net/%STARTPAGE_VERSION%/%NAME%/%VERSION%/%APPBUILDID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/\",\"updateCycleInMs\":14400000}");
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.user_id", "709199e6-c64d-481a-a565-2e3abf8780ca");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1549534862);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1549534982);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1549534622);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1549535342);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1549535222);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1549534742);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1549535462);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1549535102);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8fa93856-d75d-46a8-8e7f-e3873543be8c}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1548190800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 0);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1549534612934");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1549536425934");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1549534616781");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1549538216781");
user_pref("browser.search.region", "KE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181209160831");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1548057730");
user_pref("browser.startup.homepage_override.buildID", "20181209160831");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yahoo");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.push.userAgentID", "e1d53bedeb70448e8ea7e3893c291ce1");
user_pref("extensions.blocklist.lastModified", "Tue, 22 Jan 2019 23:05:38 GMT");
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1549534863);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181209160831");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{a243f98b-293f-4144-a6e4-95f517bf214e}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"d3013117-0f7f-496e-8191-de3959e627ed\",\"screenshots@mozilla.org\":\"7380feaf-d91e-4a93-901d-28c205fd12ec\",\"webcompat-reporter@mozilla.org\":\"2f1c4568-e3c4-4c72-ba57-6dab557cf2de\",\"webcompat@mozilla.org\":\"79ac1c44-2bea-43f5-a4c7-9dd49f023391\",\"fxmonitor@mozilla.org\":\"41192dd1-0b6c-4078-b453-7160f28d58b0\"}");
user_pref("idle.lastDailyNotification", 1549535791);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.benchmark.vp9.fps", 51);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1547995820);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181209160831");
user_pref("media.gmp-manager.lastCheck", 1549534782);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1549535791);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "0e4dc722-96a5-4187-8b02-a975196026ec");
user_pref("security.sandbox.plugin.tempDirSuffix", "02900738-10d4-4095-a9e6-4fd6e09b5f05");
user_pref("services.blocklist.addons.checked", 1549534603);
user_pref("services.blocklist.gfx.checked", 1549534603);
user_pref("services.blocklist.onecrl.checked", 1549534603);
user_pref("services.blocklist.pinning.checked", 1549534603);
user_pref("services.blocklist.plugins.checked", 1549534603);
user_pref("services.settings.clock_skew_seconds", -259);
user_pref("services.settings.last_etag", "\"1549456982474\"");
user_pref("services.settings.last_update_seconds", 1549535001);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1549534603);
user_pref("services.settings.main.language-dictionaries.last_check", 1549534603);
user_pref("services.settings.main.onboarding.last_check", 1549534603);
user_pref("services.settings.main.sites-classification.last_check", 1549534603);
user_pref("services.settings.main.tippytop.last_check", 1549534603);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1547998167);
user_pref("toolkit.startup.last_success", 1549534587);
user_pref("toolkit.telemetry.cachedClientID", "3e975357-099f-4f75-b53c-340b3112e7ab");
user_pref("toolkit.telemetry.previousBuildID", "20181209160831");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
